# Boilerplate code generated by OVITO Pro 3.7.12
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from ovito.vis import *
from ovito.qt_compat import QtCore

# Data import:
pipeline = import_file('/home/rzlin/hi00vyta/bin/Thompson_tetrahedron/ThomTet_x110_y-11-1_z-112.vtk')

# Manual modifications of the imported data objects:
def modify_pipeline_input(frame: int, data: DataCollection):
    data.triangle_meshes['mesh_'].face_count = 4
    data.triangle_meshes['mesh_'].vertex_count = 4
pipeline.modifiers.append(modify_pipeline_input)
pipeline.add_to_scene()

# User-defined modifier 'Python script':

#pipeline.modifiers.append(modify)

# Viewport setup:
vp = Viewport()
vp.type = Viewport.Type.Bottom
vp.fov = 76.578577195
#vp.camera_dir = (-0.0, -0.0, 1.0)  # for green triangle A at the bottom
vp.camera_dir = (0.0, 0.0, 1.0) 
vp.camera_up = (0.0, -1.0, 0.0)  #extra added
vp.camera_pos = (50.6743600810218, -47.762472772959875, 0.0)
vp.overlays.append(TextLabelOverlay(
    alignment = QtCore.Qt.AlignHCenter ^ QtCore.Qt.AlignTop, 
    offset_x = 0.15, 
    offset_y = 0.07, #-0.7789, 
    font_size = 0.08, 
    text = 'A', 
    text_color = (0.0, 0.0, 0.0), 
    font = 'Arial,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'))
vp.overlays.append(TextLabelOverlay(
    alignment = QtCore.Qt.AlignHCenter ^ QtCore.Qt.AlignBottom, 
    offset_x = 0.46, 
    offset_y = 0.1, 
    font_size = 0.08, 
    text = 'C', 
    text_color = (0.0, 0.0, 0.0), 
    font = 'Arial,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'))
vp.overlays.append(TextLabelOverlay(
    alignment = QtCore.Qt.AlignHCenter ^ QtCore.Qt.AlignTop, 
    offset_x = 0.0992, 
    offset_y = -0.31, 
    font_size = 0.08, 
    text = ' β', 
    text_color = (0.0, 0.0, 0.0), 
    font = 'Arial,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'))
vp.overlays.append(TextLabelOverlay(
    alignment = QtCore.Qt.AlignHCenter ^ QtCore.Qt.AlignBottom, 
    offset_x = -0.27, 
    offset_y = 0.1, 
    font_size = 0.08, 
    text = 'D', 
    text_color = (0.0, 0.0, 0.0), 
    font = 'Arial,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1'))
vp.overlays.append(CoordinateTripodOverlay(
    alignment = QtCore.Qt.AlignLeading ^ QtCore.Qt.AlignBottom, 
    size = 0.025, 
    line_width = 0.07, 
    offset_x = 0.03, #0.146, 
    offset_y = 0.04, #-0.5264, 
    font_size = 0.5, 
    axis1_label = 'x[110]', 
    axis2_label = 'y[-11-1]', 
    axis3_label = 'z[-112]', 
    axis1_color = (0.0, 0.0, 0.0), 
    axis2_color = (0.0, 0.0, 0.0), 
    axis3_color = (0.0, 0.0, 0.0)))

# Rendering:
vp.render_image(filename='/home/rzlin/hi00vyta/bin/Thompson_tetrahedron/TT.png', size=(1024, 768), background=(0.996078431372549, 0.996078431372549, 0.996078431372549))
